FROM python:3.12-trixie

# Set the working directory in the container
WORKDIR /app

# RUN apt-get update -y \
#     && apt-get install -y python-dev-is-python3 libsasl2-dev libldap2-dev libssl-dev libsnmp-dev
RUN python -m pip install --upgrade pip

# Copy the requirements file
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install pydantic[email]